In [1]:
import pandas as pd
RomTendencies = 'RomTendncyForAnova.csv'
GerTendecies = 'GerTendncyForAnova.csv'
RomTextsPerm_Tendecies = "Rom_texts_perm_for_stat_sig_test.csv"
GerTextsPerm_Tendecies = "Ger_texts_perm_for_stat_sig_test.csv"

In [11]:
rom_df = pd.read_csv(RomTendencies)
ger_df = pd.read_csv(GerTendecies)
rom_texts_df = pd.read_csv(RomTextsPerm_Tendecies)
ger_texts_df = pd.read_csv(GerTextsPerm_Tendecies)

In [12]:
rom_texts_df.head()

,group,1,2,3,4,5,6,7,8,9,...,73,74,75,76,77,78,79,80,81,82
0,low-control,0.061352,0.578839,0.084547,0.991030,0.958743,0.988409,0.760966,0.055719,0.967512,...,0.169738,0.936068,0.726446,0.720760,0.062318,0.144938,0.913539,0.429856,0.900557,0.555281
1,medium-control,0.038070,0.593494,0.067956,0.993020,0.959199,0.993131,0.777965,0.035939,0.970340,...,0.113642,0.960106,0.710308,0.721679,0.051974,0.123802,0.922010,0.407123,0.915384,0.559324
2,high-control,0.038360,0.592658,0.064271,0.993494,0.957821,0.992109,0.781157,0.038875,0.970179,...,0.136718,0.943082,0.716549,0.726256,0.054095,0.151645,0.903170,0.426196,0.908167,0.561441

In [13]:
rom_non_zero = rom_df.loc[:, (rom_df != 0).any(axis=0)]
ger_non_zero = ger_df.loc[:, (ger_df != 0).any(axis=0)]
rom_non_zero.head()

,group,7,10,19,31,32,34,37,40,41,...,197,200,204,207,210,213,217,231,234,235
0,low,1.000000,0.500000,1.000000,0.000000,0.083333,0.000000,0.073171,1.000000,0.034483,...,1.000000,0.008547,1.000000,0.363636,0.428571,1.000000,0.000000,0.571429,0.000000,0.125000
1,medium,1.000000,0.397959,0.948276,0.011364,0.045662,0.000000,0.171698,0.981481,0.024911,...,0.998134,0.023327,1.000000,0.296610,0.175573,0.962963,0.003284,0.596491,0.059603,0.566667
2,high,0.928571,0.381443,0.976190,0.000000,0.033149,0.002933,0.263298,1.000000,0.039474,...,1.000000,0.055031,0.978947,0.202020,0.147436,1.000000,0.009600,0.760000,0.072917,0.333333
3,locness,0.882353,0.208333,0.848485,0.062500,0.033898,0.000000,0.690265,0.952381,0.085366,...,1.000000,0.048023,0.980769,0.300813,0.226481,0.857143,0.400000,0.836066,0.372549,0.684211
4,cow,0.617103,0.550167,0.925715,0.226158,0.080382,0.026440,0.520151,0.912762,0.158505,...,0.986637,0.131250,0.919465,0.201367,0.313582,0.849484,0.201491,0.891362,0.305493,0.286600

In [14]:
rom_non_zero = rom_non_zero.T
ger_non_zero = ger_non_zero.T
rom_texts_df = rom_texts_df.T
ger_texts_df = ger_texts_df.T
rom_texts_df.head()

                 0               1             2
group  low-control  medium-control  high-control
1         0.061352         0.03807       0.03836
2         0.578839        0.593494      0.592658
3         0.084547        0.067956      0.064271
4          0.99103         0.99302      0.993494

In [15]:
rom_non_zero.columns = rom_non_zero.iloc[0]
rom_non_zero = rom_non_zero[1:]
ger_non_zero.columns = ger_non_zero.iloc[0]
ger_non_zero = ger_non_zero[1:]
rom_texts_df.columns = rom_texts_df.iloc[0]
rom_texts_df = rom_texts_df[1:]
ger_texts_df.columns = ger_texts_df.iloc[0]
ger_texts_df = ger_tests_df[1:]
rom_texts_df

group low-control medium-control high-control
1        0.061352        0.03807      0.03836
2        0.578839       0.593494     0.592658
3        0.084547       0.067956     0.064271
4         0.99103        0.99302     0.993494
5        0.958743       0.959199     0.957821
..            ...            ...          ...
78       0.144938       0.123802     0.151645
79       0.913539        0.92201      0.90317
80       0.429856       0.407123     0.426196
81       0.900557       0.915384     0.908167
82       0.555281       0.559324     0.561441

[82 rows x 3 columns]

In [16]:
groups = list(rom_texts_df.columns)
groups

['low-control', 'medium-control', 'high-control']

In [19]:
import scipy.stats as stats 
pairs = {}
for origin in ['rom', 'ger']:
    pairs[origin] = {}
    for grp1 in groups:
        for grp2 in groups:
            if grp1 == grp2 or "{},{}".format(grp1, grp2) in pairs.keys() or "{},{}".format(grp2, grp1) in pairs.keys():
                continue
            if origin == 'rom':
                non_zero_df = rom_texts_df
            else:
                non_zero_df = ger_tests_df
            fvalue, pvalue = stats.kruskal(non_zero_df[grp1], non_zero_df[grp2])
            pairs[origin]["{},{}".format(grp1, grp2)] = pvalue

In [20]:
pairs

{'rom': {'low-control,medium-control': 0.8616255104006612,
  'low-control,high-control': 0.879751791464584,
  'medium-control,low-control': 0.8616255104006612,
  'medium-control,high-control': 0.9816331559027734,
  'high-control,low-control': 0.879751791464584,
  'high-control,medium-control': 0.9816331559027734},
 'ger': {'low-control,medium-control': 0.8519340379411444,
  'low-control,high-control': 0.9174112601920785,
  'medium-control,low-control': 0.8519340379411444,
  'medium-control,high-control': 0.787462275465711,
  'high-control,low-control': 0.9174112601920785,
  'high-control,medium-control': 0.787462275465711}}

In [102]:
fvalue, pvalue = stats.kruskal(rom_non_zero['low'], rom_non_zero['medium'], rom_non_zero['high'], rom_non_zero['locness'], rom_non_zero['cow'])
print(fvalue, pvalue)

6.138838224909178 0.18901690047856054

In [103]:
fvalue, pvalue = stats.kruskal(ger_non_zero['low'], ger_non_zero['medium'], ger_non_zero['high'], ger_non_zero['locness'], ger_non_zero['cow'])
print(fvalue, pvalue)

28.545651486855327 9.667405492023465e-06

In [22]:
fvalue, pvalue = stats.kruskal(rom_texts_df['low-control'], rom_texts_df['high-control'], rom_texts_df['medium-control'])
print(fvalue, pvalue)

0.035466646756844966 0.9824229866712483

In [23]:
fvalue, pvalue = stats.kruskal(ger_texts_df['low-control'], ger_texts_df['high-control'], ger_texts_df['medium-control'])
print(fvalue, pvalue)

0.1025154247745661 0.9500338035016487

In [85]:
import os

['0',
 '1',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '2',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '3',
 '30',
 '31',
 '32',
 '33',
 '34',
 '35',
 '36',
 '37',
 '38',
 '39',
 '4',
 '40',
 '41',
 '42',
 '43',
 '44',
 '45',
 '46',
 '47',
 '48',
 '49',
 '5',
 '50',
 '51',
 '52',
 '53',
 '54',
 '55',
 '56',
 '57',
 '58',
 '59',
 '6',
 '60',
 '61',
 '62',
 '63',
 '64',
 '65',
 '66',
 '67',
 '68',
 '69',
 '7',
 '70',
 '71',
 '72',
 '73',
 '74',
 '75',
 '76',
 '77',
 '78',
 '79',
 '8',
 '80',
 '81',
 '82',
 '83',
 '84',
 '85',
 '86',
 '87',
 '88',
 '89',
 '9',
 '90',
 '91',
 '92',
 '93',
 '94',
 '95',
 '96',
 '97',
 '98',
 '99']

In [88]:
for i in range(100):
    folder = os.path.join(rom_perm_test_inputs, str(i))
    for f in os.listdir(folder):
        with open(os.path.join(folder,f), 'rb') as obj:
            content = pickle.load(obj)
            print(content)
            break
        break

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)